/**
 * What is not the project.
 *
 * Directories that exist on disk but are not source: dependencies, VCS internals,
 * build output, tool caches, and this harness's own index directory. Anything that
 * WALKS or SEARCHES a project tree should skip them — a graph index, a file search,
 * a summary pass.
 *
 * This lives at the root, with no imports, for the same reason `code-risk.ts` does:
 * it is shared by modules that must not depend on each other. The list was being
 * re-typed per call site — graph indexing had one, the activity monitor's file walk
 * had a shorter one, `grep` had a third — so a directory learned in one place
 * stayed unknown in the others.
 *
 * The first attempt at fixing that exported the list from `graph-memory.ts` and
 * imported it into the coding tools, which was worse than the duplication: it made
 * `coding.ts` — the module every tool call loads — pull in the graph subsystem and
 * all sixteen of its language adapters to read one array of strings. A constant
 * shared by two subsystems belongs to neither.
 */

/**
 * Skipped by every tree walk and search: directory names that are build output, dependency trees, or tool caches in
 * some ecosystem, matched by NAME AT ANY DEPTH — not just at the project root.
 *
 * Depth matters: a Flutter app keeps its artifacts in a top-level `build/`, a
 * Gradle module keeps them in `android/app/build/`, and a monorepo has one
 * `node_modules` per package. A root-only list indexed 10k `flutter_assets`
 * icons on a real project and paid for an LLM summary of each one.
 *
 * Every name here is generated by strong convention. Names that are *sometimes*
 * generated and sometimes hand-written source (`lib`, `public`, `assets`, `env`,
 * `var`, `tmp`, `gradle`, `.vscode`, Unity's `Library`) are deliberately absent:
 * skipping real source is a worse failure than summarizing a few artifacts.
 *
 * The harness's own memory directory is in here, and it earns its place by
 * observation: it holds a generated symbol index that mentions every symbol in the
 * project, so before it was excluded a search for any symbol returned its index
 * entries and nothing else. A model reads "the only hits are inside a JSON blob" as
 * "there are no real call sites". An artifact we generate must never come back as a
 * search result.
 */
export const IGNORED_PROJECT_DIRS: readonly string[] = [
  // Version control, editors, OS
  ".git",
  ".hg",
  ".svn",
  ".bzr",
  ".jj",
  ".idea",
  ".vs",
  ".fleet",
  ".history",
  "__MACOSX",
  // Generic build output / compiler artifacts
  ".build",
  "_build",
  "build",
  "Build",
  "builds",
  "bin",
  "obj",
  "out",
  ".out",
  ".output",
  "dist",
  "target",
  "CMakeFiles",
  "cmake-build-debug",
  "cmake-build-release",
  // Dependency trees
  "node_modules",
  "bower_components",
  "jspm_packages",
  "vendor",
  // NOT "packages" — pnpm/Turborepo/Lerna monorepos keep real source there.
  "deps",
  "site-packages",
  // JS / TS toolchains and frameworks
  ".angular",
  ".astro",
  ".cache",
  ".docusaurus",
  ".next",
  ".nuxt",
  ".nx",
  ".parcel-cache",
  ".pnpm-store",
  ".rollup.cache",
  ".rush",
  ".sass-cache",
  ".svelte-kit",
  ".swc",
  ".turbo",
  ".vite",
  ".webpack",
  ".yarn",
  "storybook-static",
  // Test / coverage reports
  "coverage",
  "htmlcov",
  "playwright-report",
  "test-results",
  "TestResults",
  ".nyc_output",
  ".phpunit.cache",
  // Python
  "__pycache__",
  ".eggs",
  ".hypothesis",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pdm-build",
  ".pixi",
  ".pytest_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "venv",
  ".conda",
  // JVM (Java / Kotlin / Scala / Clojure)
  ".gradle",
  ".kotlin",
  ".m2",
  ".bloop",
  ".bsp",
  ".metals",
  ".cpcache",
  ".shadow-cljs",
  "kotlin-js-store",
  // Android
  ".cxx",
  ".externalNativeBuild",
  "captures",
  // Apple (iOS / macOS / Swift)
  "Carthage",
  "DerivedData",
  "Pods",
  ".swiftpm",
  ".symlinks",
  "xcuserdata",
  // Flutter / Dart
  ".dart_tool",
  ".pub-cache",
  "flutter_assets",
  "ephemeral",
  // React Native / Expo
  ".expo",
  ".expo-shared",
  // Ruby
  ".bundle",
  // Elixir / Erlang / Haskell
  ".elixir_ls",
  ".stack-work",
  "dist-newstyle",
  // Zig / C / C++ language servers
  ".zig-cache",
  "zig-cache",
  "zig-out",
  ".ccls-cache",
  ".clangd",
  // Bazel / Buck / Pants
  "bazel-bin",
  "bazel-out",
  "bazel-testlogs",
  "buck-out",
  ".pants.d",
  // Infra / cloud / serverless
  ".terraform",
  ".terragrunt-cache",
  ".serverless",
  ".aws-sam",
  "cdk.out",
  ".vercel",
  ".netlify",
  ".wrangler",
  ".firebase",
  // Static site generators
  "_site",
  ".jekyll-cache",
  ".quarto",
  // Game engines
  ".godot",
  ".import",
  // ML / data
  "mlruns",
  "wandb",
  // Shell / env tooling and our own store
  ".direnv",
  ".turing",
];

/**
 * Directories only a TEXT SEARCH encounters, on top of the shared list.
 *
 * A tree walk that indexes source never opens these; `grep -r` happily does, and
 * one of them is usually the largest thing in the repo. Empty now that the shared
 * list covers `Pods` and `Carthage` by name at any depth — kept as the seam for
 * the next search-only exclusion.
 */
export const GREP_ONLY_EXCLUDED_DIRS: readonly string[] = [];
